#! /bin/sh

sxhkd &
dunst &
picom &

count=$(xrandr --listmonitors | cut -d " " -f 3 | tail +2 | wc -l)

if [[ count -eq 2 ]]
then
    # two monitor setup
    bspc monitor HDMI-1 -d I III V
    bspc monitor DVI-D-1 -D II IV VI
else
    # single monitor setup
    bspc monitor -d I II III IV V VI
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
