export PATH=$PATH:~/.local/bin:~/go/bin:~/.cargo/bin:~/.emacs.d/bin
export BROWSER=firefox
export EDITOR=nvim

export FZF_BASE=/usr/share/fzf
export FZF_DEFAULT_COMMAND=fzf

alias latex="latexmk -lualatex -pvc -interaction=nonstopmode"
alias cat="bat --style plain"
alias c='cd $(find * -type d | fzf); pwd'
alias cl='sbcl --eval "(asdf:load-system \"sbcl-readline\")"'

setopt PROMPT_SUBST
PROMPT="%F{white}%~%f%F{178} λ%f "

bindkey -s '^g' '\\
    | grep '
[ -f "/home/dylan/.ghcup/env" ] && source "/home/dylan/.ghcup/env" # ghcup-env

function md() {
    infile=$1
    outfile=$(echo "$infile" | sed "s/.md$/.pdf/")
    pandoc "$infile" -f gfm --template eisvogel -o "$outfile" --listings
}

function clearswap() {
    rm -f ~/.local/state/nvim/swap/*
}

function spotd() {
    killall spotifyd
    pw="$(pass spotify/spotify.com)"
    spotifyd --no-daemon --username "dylan.connor-de" --password "$pw" --backend "pulseaudio"
}

# opam configuration
[[ ! -r /home/dylan/.opam/opam-init/init.zsh ]] || source /home/dylan/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

source ~/.zsh/zsh-fzy.plugin.zsh
bindkey '\ec' fzy-cd-widget
bindkey '^F'  fzy-file-widget
bindkey '^R'  fzy-history-widget
bindkey '^P'  fzy-proc-widget

zstyle :fzy:file command fd -I --one-file-system --type f
zstyle :fzy:cd command fd -I --one-file-system --type d

alias mkpdftex="latexmk -pvc -lualatex -f- -interaction=nonstopmode"

alias bt="bluetoothctl"
alias startx="sway"

# bun completions
[ -s "/home/dylan/.bun/_bun" ] && source "/home/dylan/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
