export PATH=$PATH:~/.local/bin:~/go/bin:~/.cargo/bin:~/.emacs.d/bin
export BROWSER=librewolf
export EDITOR=nvim
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

export FZF_BASE=/usr/share/fzf
export FZF_DEFAULT_COMMAND=fzf

alias latex="latexmk -lualatex -pvc -interaction=nonstopmode"
alias cat="bat --style plain"
alias c='cd $(find * -type d | fzf); pwd'
alias cl='sbcl --eval "(asdf:load-system \"sbcl-readline\")"'

setopt PROMPT_SUBST
PROMPT="[%F{white}%~%f] %F{178}λ%f "

bindkey -s '^g' '\\
    | grep '

function md() {
    infile=$1
    outfile=$(echo "$infile" | sed "s/.md$/.pdf/")
    pandoc "$infile" -f gfm --template eisvogel -o "$outfile" --listings
}

function clearswap() {
    rm -f ~/.local/state/nvim/swap/*
}

function spotd() {
    killall spotifyd
    pw="$(pass spotify/spotify.com)"
    spotifyd --no-daemon --username "dylan.connor-de" --password "$pw" --backend "pulseaudio"
}

# opam configuration
[[ ! -r /home/dylan/.opam/opam-init/init.zsh ]] || source /home/dylan/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

source ~/.zsh/zsh-fzy.plugin.zsh
bindkey '^D'  fzy-cd-widget
bindkey '^F'  fzy-file-widget
bindkey '^R'  fzy-history-widget
bindkey '^P'  fzy-proc-widget

zstyle :fzy:file command fd -I --one-file-system --type f
zstyle :fzy:cd command fd -I --one-file-system --type d

alias mkpdftex="latexmk -pvc -lualatex -f- -interaction=nonstopmode"

alias l='lsd -l'

alias bt="bluetoothctl"
alias startx="sway"

# bun completions
[ -s "/home/dylan/.bun/_bun" ] && source "/home/dylan/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
export TERM=xterm-256color

dff() {
    for x in "$@"
    do
        df -h "$x" \
            | awk 'NR == 2 {print "'"$x"': " $3 "/" $2}'
    done
}

mdd() {
    while true 
    do
        dff "$@"
        sleep 5
        for x in "$@"
        do
            echo -ne '\e[A\r\e[K'
        done
    done
}

boop() {
    play -n synth 0.05 sin 1000 $@ 2>/dev/null
}
beep() {
    play -n synth 0.1 sin 1000 sin 800 $@ delay 0 +0.1 2>/dev/null
}

ncc() {
    for p in "${@:2}"
    do
        echo -n "\e[K$p: "
        nc -zw1 $1 $p
        if [ "$?" -eq 0 ]
        then
            echo -e "\r\e[K$p: open."
            beep
        else
            echo -ne "closed.\r"
            boop
            sleep 0.2
        fi
    done
    echo -ne "\r\e[K"
}
ncw() {
    echo -ne "\e[K...\r"
    while true
    do
        nc -zw2 $1 $2
        if [ "$?" -eq 0 ]
        then
            echo -e "\e[K$1 $2: open."
            beep
            break
        else
            echo -ne "\e[K$1 $2: closed.\r"
            boop vol 0.3
            sleep 2
        fi
        echo -ne "\e[K...\r"
    done
}
sshw() {
    ncw $1 22 && ssh $@
}
alias ytdl="yt-dlp -t mp4 -o '%(uploader)s/%(upload_date)s %(id)s %(title)s.%(ext)s'"
alias ytdlx="yt-dlp -o '%(uploader)s/%(upload_date)s %(id)s %(title)s.%(ext)s' --extract-audio -t mp3"

dl() {
    ytdl -t mp4 --download-archive "archive.txt" "$@"
}
dlx() {
    ytdlx --download-archive "archive.txt" "$@"
}

alias rcp='rsync --progress'
alias srcp='sudo rsync --progress'
alias ffprobe='ffprobe -hide_banner'

[ -f "/home/dylan/.ghcup/env" ] && . "/home/dylan/.ghcup/env" # ghcup-env
